export const data = {
  glbUrl: "/Laundry.glb",
  varibles: {
    allwidth: 2400,
    baseOneTexture: "Texture 1",
    baseTwoTexture: "Texture 1",
    topOneTexture: "Texture 1",
    topTwoTexture: "Texture 1",
    tallTexture: "Texture 1",
    baseHeight: 730,
    baseDepth: 580,
    topHeight: 730,
    topDepth: 320,
    tallHeight: 2200,
    tallDepth: 600,
    tallWidth: 930,
    bulkHeadHeight: 300,
    kickerHeight: 140,
    baseOneWidth: 800,
    baseTwoWidth: 600,
    topOneWidth: 700,
    topTwoWidth: 700,
    borderColor: "#ff0000",
    borderThickness: 0.05,
  },
  nodesData: [
    {
      name: "baseOne",
      nodes: ["3DGeom-10"],
      label: "Base One",
      material: "baseOne",
      controls: {
        baseOneWidth: {
          value: 800,
          min: 500,
          max: 1000,
          step: 10,
          label: "Width",
        },
        baseHeight: {
          value: 730,
          min: 500,
          max: 1000,
          step: 10,
          label: "Height",
        },
        baseDepth: {
          value: 580,
          min: 400,
          max: 800,
          step: 10,
          label: "Depth",
        },
        baseOneTexture: {
          value: "Texture 1",
          options: [
            "Texture 1",
            "Texture 2",
            "Texture 3",
            "Texture 4",
            "Texture 5",
          ],
          label: "Texture",
        },
      },
    },
    {
      name: "baseTwoWidth",
      nodes: ["3DGeom-11"],
      label: "Base Two",
      material: "baseTwo",
      controls: {
        baseTwoWidth: {
          value: 600,
          min: 500,
          max: 1000,
          step: 10,
          label: "Width",
        },
        baseHeight: {
          value: 730,
          min: 500,
          max: 1000,
          step: 10,
          label: "Height",
        },
        baseDepth: {
          value: 580,
          min: 400,
          max: 800,
          step: 10,
          label: "Depth",
        },
        baseTwoTexture: {
          value: "Texture 1",
          options: [
            "Texture 1",
            "Texture 2",
            "Texture 3",
            "Texture 4",
            "Texture 5",
          ],
          label: "Texture",
        },
      },
      scales: [],
    },
    {
      name: "topTwoWidth",
      nodes: ["3DGeom-6"],
      label: "Top Two",
      material: "topTwo",
      controls: {
        topTwoWidth: {
          value: 700,
          min: 500,
          max: 900,
          step: 10,
          label: "Width",
        },
        topHeight: {
          value: 730,
          min: 500,
          max: 900,
          step: 10,
          label: "Height",
        },
        topDepth: {
          value: 320,
          min: 200,
          max: 500,
          step: 10,
          label: "Depth",
        },
        topTwoTexture: {
          value: "Texture 1",
          options: [
            "Texture 1",
            "Texture 2",
            "Texture 3",
            "Texture 4",
            "Texture 5",
          ],
          label: "Texture",
        },
      },
    },
    {
      name: "topOneWidth",
      nodes: ["3DGeom-7"],
      label: "Top One",
      material: "topOne",
      controls: {
        topOneWidth: {
          value: 700,
          min: 500,
          max: 900,
          step: 10,
          label: "Width",
        },
        topHeight: {
          value: 730,
          min: 500,
          max: 900,
          step: 10,
          label: "Height",
        },
        topDepth: {
          value: 320,
          min: 200,
          max: 500,
          step: 10,
          label: "Depth",
        },
        topOneTexture: {
          value: "Texture 1",
          options: [
            "Texture 1",
            "Texture 2",
            "Texture 3",
            "Texture 4",
            "Texture 5",
          ],
          label: "Texture",
        },
      },
    },
    {
      name: "tallGroup",
      nodes: ["3DGeom-1", "3DGeom-2", "3DGeom-8"],
      label: "Tall Group",
      material: "tall",
      controls: {
        tallWidth: {
          value: 930,
          min: 500,
          max: 2000,
          step: 10,
          label: "Width",
        },
        tallHeight: {
          value: 2200,
          min: 1700,
          max: 2500,
          step: 10,
          label: "Height",
        },
        tallDepth: {
          value: 600,
          min: 300,
          max: 700,
          step: 10,
          label: "Depth",
        },
        tallTexture: {
          value: "Texture 1",
          options: [
            "Texture 1",
            "Texture 2",
            "Texture 3",
            "Texture 4",
            "Texture 5",
          ],
          label: "Texture",
        },
      },
    },
    {
      name: "bulkHead Group",
      nodes: ["3DGeom-3", "3DGeom-4", "3DGeom-5"],
      label: "bulkHead Group",
      controls: {
        bulkHeadHeight: {
          value: 300,
          min: 100,
          max: 500,
          step: 10,
          label: "Height",
        },
      },
    },
    {
      name: "kickerGroup",
      nodes: ["3DGeom-9", "3DGeom-15", "3DGeom-16"],
      label: "kickerGroup",
      controls: {
        kickerHeight: {
          value: 140,
          min: 100,
          max: 300,
          step: 10,
          label: "Height",
        },
      },
    },
  ],
  scales: [
    {
      node: "Assembly-22",
      axis: "y",
      param: "allwidth",
      baseValue: 2400000,
    },
    { node: "3DGeom-10", axis: "y", param: "baseDepth", baseValue: 580 },
    { node: "3DGeom-11", axis: "y", param: "baseDepth", baseValue: 580 },
    { node: "3DGeom-12", axis: "y", param: "baseDepth", baseValue: 580 },
    { node: "3DGeom-13", axis: "y", param: "baseDepth", baseValue: 580 },
    { node: "3DGeom-14", axis: "y", param: "baseDepth", baseValue: 580 },
    { node: "3DGeom-15", axis: "y", param: "baseDepth", baseValue: 580 },
    { node: "3DGeom-16", axis: "y", param: "baseDepth", baseValue: 580 },
    { node: "3DGeom-10", axis: "z", param: "baseHeight", baseValue: 730 },
    { node: "3DGeom-11", axis: "z", param: "baseHeight", baseValue: 730 },
    { node: "3DGeom-10", axis: "x", param: "baseOneWidth", baseValue: 800 },
    { node: "3DGeom-13", axis: "x", param: "baseOneWidth", baseValue: 800 },
    { node: "3DGeom-16", axis: "x", param: "baseOneWidth", baseValue: 800 },
    { node: "3DGeom-9", axis: "z", param: "kickerHeight", baseValue: 140 },
    { node: "3DGeom-15", axis: "z", param: "kickerHeight", baseValue: 140 },
    { node: "3DGeom-16", axis: "z", param: "kickerHeight", baseValue: 140 },
    { node: "3DGeom-1", axis: "z", param: "tallHeight", baseValue: 2200 },
    { node: "3DGeom-1", axis: "y", param: "tallDepth", baseValue: 600 },
    { node: "3DGeom-2", axis: "y", param: "tallDepth", baseValue: 600 },
    { node: "3DGeom-3", axis: "y", param: "tallDepth", baseValue: 600 },
    { node: "3DGeom-8", axis: "y", param: "tallDepth", baseValue: 600 },
    { node: "3DGeom-9", axis: "y", param: "tallDepth", baseValue: 600 },
    { node: "3DGeom-4", axis: "y", param: "topDepth", baseValue: 320 },
    { node: "3DGeom-5", axis: "y", param: "topDepth", baseValue: 320 },
    { node: "3DGeom-6", axis: "y", param: "topDepth", baseValue: 320 },
    { node: "3DGeom-7", axis: "y", param: "topDepth", baseValue: 320 },
    { node: "3DGeom-6", axis: "z", param: "topHeight", baseValue: 730 },
    { node: "3DGeom-7", axis: "z", param: "topHeight", baseValue: 730 },
    { node: "3DGeom-7", axis: "x", param: "topOneWidth", baseValue: 700 },
    { node: "3DGeom-5", axis: "x", param: "topOneWidth", baseValue: 700 },
    { node: "3DGeom-4", axis: "x", param: "topTwoWidth", baseValue: 700 },
    { node: "3DGeom-6", axis: "x", param: "topTwoWidth", baseValue: 700 },
    { node: "3DGeom-11", axis: "x", param: "baseTwoWidth", baseValue: 600 },
    { node: "3DGeom-12", axis: "x", param: "baseTwoWidth", baseValue: 600 },
    { node: "3DGeom-15", axis: "x", param: "baseTwoWidth", baseValue: 600 },
    {
      node: "3DGeom-1",
      axis: "x",
      value: (params) => params.tallWidth - 30,
      baseValue: 900,
    },
    { node: "3DGeom-3", axis: "x", param: "tallWidth", baseValue: 930 },
    {
      node: "3DGeom-9",
      axis: "x",
      value: (params) => params.tallWidth - 30,
      baseValue: 900,
    },
    {
      node: "3DGeom-3",
      axis: "z",
      param: "bulkHeadHeight",
      baseValue: 300,
    },
    {
      node: "3DGeom-4",
      axis: "z",
      param: "bulkHeadHeight",
      baseValue: 300,
    },
    {
      node: "3DGeom-5",
      axis: "z",
      param: "bulkHeadHeight",
      baseValue: 300,
    },
    {
      node: "3DGeom-14",
      axis: "z",
      value: (params) => params.baseHeight + params.kickerHeight,
      baseValue: 870,
    },
    {
      node: "3DGeom-2",
      axis: "z",
      value: (params) => params.tallHeight + params.kickerHeight,
      baseValue: 2340,
    },
    {
      node: "3DGeom-8",
      axis: "z",
      value: (params) => params.tallHeight + params.kickerHeight,
      baseValue: 2340,
    },
  ],
  positions: [
    {
      node: "3DGeom-11",
      axis: "x",
      offsets: [
        { param: "baseOneWidth", baseValue: 800 },
        { param: "tallWidth", baseValue: 930 },
      ],
    },
    {
      node: "3DGeom-12",
      axis: "x",
      offsets: [
        { param: "baseOneWidth", baseValue: 800 },
        { param: "tallWidth", baseValue: 930 },
      ],
    },
    {
      node: "3DGeom-14",
      axis: "x",
      offsets: [
        { param: "baseOneWidth", baseValue: 800 },
        { param: "baseTwoWidth", baseValue: 600 },
        { param: "tallWidth", baseValue: 930 },
      ],
    },
    {
      node: "3DGeom-15",
      axis: "x",
      offsets: [
        { param: "baseOneWidth", baseValue: 800 },
        { param: "tallWidth", baseValue: 930 },
      ],
    },
    {
      node: "3DGeom-4",
      axis: "x",
      offsets: [
        { param: "topOneWidth", baseValue: 700 },
        { param: "tallWidth", baseValue: 930 },
      ],
    },
    {
      node: "3DGeom-6",
      axis: "x",
      offsets: [
        { param: "topOneWidth", baseValue: 700 },
        { param: "tallWidth", baseValue: 930 },
      ],
    },

    {
      node: "3DGeom-3",
      axis: "z",
      offsets: [
        { param: "tallHeight", baseValue: 2200 },
        { param: "kickerHeight", baseValue: 140 },
      ],
    },
    {
      node: "3DGeom-4",
      axis: "z",
      offsets: [
        { param: "tallHeight", baseValue: 2200 },
        { param: "kickerHeight", baseValue: 140 },
      ],
    },
    {
      node: "3DGeom-5",
      axis: "z",
      offsets: [
        { param: "tallHeight", baseValue: 2200 },
        { param: "kickerHeight", baseValue: 140 },
      ],
    },
    {
      node: "3DGeom-6",
      axis: "z",
      offsets: [
        { param: "tallHeight", baseValue: 2200 },
        { param: "kickerHeight", baseValue: 140 },
      ],
    },
    {
      node: "3DGeom-7",
      axis: "z",
      offsets: [
        { param: "tallHeight", baseValue: 2200 },
        { param: "kickerHeight", baseValue: 140 },
      ],
    },

    {
      node: "3DGeom-2",
      axis: "x",
      offsets: [{ param: "tallWidth", baseValue: 930 }],
    },
    {
      node: "3DGeom-10",
      axis: "x",
      offsets: [{ param: "tallWidth", baseValue: 930 }],
    },
    {
      node: "3DGeom-7",
      axis: "x",
      offsets: [{ param: "tallWidth", baseValue: 930 }],
    },
    {
      node: "3DGeom-5",
      axis: "x",
      offsets: [{ param: "tallWidth", baseValue: 930 }],
    },
    {
      node: "3DGeom-16",
      axis: "x",
      offsets: [{ param: "tallWidth", baseValue: 930 }],
    },
    {
      node: "3DGeom-13",
      axis: "x",
      offsets: [{ param: "tallWidth", baseValue: 930 }],
    },

    {
      node: "3DGeom-1",
      axis: "z",
      offsets: [{ param: "kickerHeight", baseValue: 140 }],
    },
    {
      node: "3DGeom-10",
      axis: "z",
      offsets: [{ param: "kickerHeight", baseValue: 140 }],
    },
    {
      node: "3DGeom-11",
      axis: "z",
      offsets: [{ param: "kickerHeight", baseValue: 140 }],
    },

    {
      node: "3DGeom-12",
      axis: "z",
      offsets: [
        { param: "baseHeight", baseValue: 730 },
        { param: "kickerHeight", baseValue: 140 },
      ],
    },
    {
      node: "3DGeom-13",
      axis: "z",
      offsets: [
        { param: "baseHeight", baseValue: 730 },
        { param: "kickerHeight", baseValue: 140 },
      ],
    },
  ],
  textureConfig: [
    {
      pattern: "baseOne",
      textureParam: "baseOneTexture",
      nodeName: "3DGeom-10",
      baseWidth: 800,
      maxWidth: 1000,
      baseHeight: 730,
      maxHeight: 1000,
    },
    {
      pattern: "baseTwo",
      textureParam: "baseTwoTexture",
      nodeName: "3DGeom-11",
      baseWidth: 600,
      maxWidth: 1000,
      baseHeight: 730,
      maxHeight: 1000,
    },
    {
      pattern: "topOneWidth",
      textureParam: "topOneTexture",
      nodeName: "3DGeom-7",
      baseWidth: 700,
      maxWidth: 900,
      baseHeight: 730,
      maxHeight: 900,
    },
    {
      pattern: "topTwoWidth",
      textureParam: "topTwoTexture",
      nodeName: "3DGeom-6",
      baseWidth: 700,
      maxWidth: 900,
      baseHeight: 730,
      maxHeight: 900,
    },
    {
      pattern: "tall",
      textureParam: "tallTexture",
      nodeName: "3DGeom-1",
      baseWidth: 930,
      maxWidth: 2000,
      baseHeight: 2200,
      maxHeight: 2500,
    },
  ],
  textures: [
    "/textures/material1.jpg",
    "/textures/material2.jpg",
    "/textures/material3.jpg",
    "/textures/material4.jpg",
    "/textures/material5.jpeg",
  ],
};
