export const data = {
  glbUrl: "/Laundry.glb",
  varibles: {
    baseOneTexture: "Texture 1",
    baseTwoTexture: "Texture 1",
    topOneTexture: "Texture 1",
    topTwoTexture: "Texture 1",
    tallTexture: "Texture 1",
    baseHeight: 730,
    baseDepth: 580,
    topHeight: 730,
    topDepth: 320,
    tallHeight: 2200,
    tallDepth: 600,
    tallWidth: 930,
    bulkHeadHeight: 300,
    kickerHeight: 140,
    baseOneWidth: 800,
    baseTwoWidth: 600,
    topOneWidth: 700,
    topTwoWidth: 700,
  },
  nodesData: [],
  scales: [],
  positions: [],
};
