// This file was generated by a script
// Contains exported data for room: 8253887608403-room-f83cfca1-4a1d-4d69-9d01-e5d68bdba8b9

export const roomData: RoomExportData = {
  "glbUrl": "https://firebasestorage.googleapis.com/v0/b/cublux-221911.appspot.com/o/companies%2FMCRKFzMMkEzvhzS8JrDQ%2FwsRooms%2FroomFiles%2Fsample.glb_8253528285992-4f7b33ab-063b-468c-900e-3087b54aa417.glb?alt=media&token=ab8c8a58-377f-4e5a-984c-bfa7f5f909db",
  "configuredNodes": [
    {
      "productId": "8258174240533-Product-c5eb9f24-0257-4ce5-afcd-6d1571477303",
      "nodeName": "3DGeom-11",
      "isVisible": true,
      "productLabel": "Base Single Left Door Custom Cabinet",
      "dimensions": {
        "x": {
          "dimensionId": "8260381186817-dim-847ff9ec-3631-48f4-a0f7-f016272146ec",
          "dimensionLabel": "Depth",
          "defaultValue": 90,
          "min": 90,
          "max": 1000,
          "positionPreceders": [
            "3DGeom-12"
          ],
          "valueType": "range",
          "options": [],
          "oppositeNode": "3DGeom-12"
        },
        "y": {
          "dimensionId": "8261314903663-dim-5e312aa4-a998-4369-92d6-1288fc9f77dc",
          "dimensionLabel": "Width",
          "defaultValue": 91,
          "min": 150,
          "max": 610,
          "positionPreceders": [
            "3DGeom-12"
          ],
          "valueType": "range",
          "options": []
        },
        "z": {
          "dimensionId": "8261315085495-dim-40d0af67-6436-4be6-a8eb-499733c38e6e",
          "dimensionLabel": "Height",
          "defaultValue": 92,
          "min": 400,
          "max": 1200,
          "positionPreceders": [
            "3DGeom-12"
          ],
          "valueType": "range",
          "options": [],
          "oppositeNode": "3DGeom-12"
        }
      }
    },
    {
      "productId": "8255896915810-Product-62739c7f-77b1-4195-80e4-5c5105be0ea6",
      "nodeName": "3DGeom-12",
      "isVisible": false,
      "productLabel": "Base Right Blind Single Door Cabinet",
      "dimensions": {
        "x": {
          "dimensionId": "8260381186817-dim-847ff9ec-3631-48f4-a0f7-f016272146ec",
          "dimensionLabel": "Depth",
          "defaultValue": 0,
          "min": 90,
          "max": 1000,
          "positionPreceders": [],
          "valueType": "range",
          "options": []
        },
        "y": {
          "dimensionId": "8261314903663-dim-5e312aa4-a998-4369-92d6-1288fc9f77dc",
          "dimensionLabel": "Width",
          "defaultValue": 0,
          "min": 400,
          "max": 1200,
          "positionPreceders": [],
          "valueType": "range",
          "options": []
        },
        "z": {
          "dimensionId": "8261315085495-dim-40d0af67-6436-4be6-a8eb-499733c38e6e",
          "dimensionLabel": "Height",
          "defaultValue": 0,
          "min": 400,
          "max": 1200,
          "positionPreceders": [],
          "valueType": "range",
          "options": []
        }
      }
    }
  ],
  "roomId": "8253887608403-room-f83cfca1-4a1d-4d69-9d01-e5d68bdba8b9",
  "roomName": "Test By Dev"
}

// --- Type Definitions ---

export interface RoomExportData {
  roomId: string
  roomName: string
  glbUrl: string // The full url of the GLB file associated with this room
  configuredNodes: NodeConfiguration[] // An array of all nodes configured in this room
}

export interface NodeConfiguration {
  nodeName: string // e.g., "3DGeom-10" - The primary identifier for the 3D side
  productId: string // e.g., "product_xyz" - For reference/debugging
  productLabel: string // e.g., "Base Single Left Door Custom Cabinet" - For context
  isVisible: boolean // Current visibility state

  dimensions: {
    x: AxisConfiguration
    y: AxisConfiguration
    z: AxisConfiguration
  }
}

export interface AxisConfiguration {
  dimensionId: string // The controlling dimension ID from WsProduct
  dimensionLabel: string // User-friendly label (from WsProduct.dims[dimensionId].dim or WsRoomProductsAxis.label)
  defaultValue: number // The default/current value set in the control panel

  min: number
  max: number

  valueType: "range" | "selection" // The type of the value of this dimension
  options?: number[] // only for selection type, the available options for this dimension

  // --- Positional Relationship Hints ---
  positionPreceders: string[] // List of NODE NAMES that this node follows along this axis
  oppositeNode?: string // The NODE NAME of the opposite element, if defined
}
